const catalogo = [
  {
    "imagen": "20230511_175750",
    "producto": "pestañas pxp",
    "descripcion": "mix nagaraku",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "pestañas pxp mix nagaraku",
    "costo": 1240,
    "margenBeneficio": 41,
    "stock": 10,
    "oferta": 1,
    "precio": 2100,
    "ganancia": 860
  },
  {
    "imagen": "broches",
    "producto": "broches para poligel ",
    "descripcion": " x 1 u ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "broches para poligel   x 1 u ",
    "costo": 80,
    "margenBeneficio": 45,
    "stock": 12,
    "precio": 150,
    "ganancia": 70
  },
  {
    "imagen": "20230318_103332",
    "producto": "brocha",
    "descripcion": "de maquilleje x 5",
    "categoria": "maquillaje",
    "nombreProducto": "brocha de maquilleje x 5",
    "costo": 600,
    "margenBeneficio": 40,
    "stock": 2,
    "precio": 1000,
    "ganancia": 400
  },
  {
    "imagen": "20230321_190416",
    "producto": "porta pincel",
    "descripcion": "de acrilico",
    "categoria": "organizadores",
    "nombreProducto": "porta pincel de acrilico",
    "costo": 800,
    "margenBeneficio": 40,
    "stock": 0,
    "precio": 1330,
    "ganancia": 530
  },
  {
    "imagen": "20230425_105827",
    "producto": "ventilador de pestaña ",
    "descripcion": " consultar color",
    "categoria": "electronico",
    "nombreProducto": "ventilador de pestaña   consultar color",
    "costo": 1900,
    "margenBeneficio": 50,
    "stock": 3,
    "precio": 3800,
    "ganancia": 1900
  },
  {
    "imagen": "20230429_100914",
    "producto": "mascarilla",
    "descripcion": "de colageno para ojeras ",
    "categoria": "cuidado personal",
    "nombreProducto": "mascarilla de colageno para ojeras ",
    "costo": 110,
    "margenBeneficio": 30,
    "stock": 2,
    "precio": 160,
    "ganancia": 50
  },
  {
    "imagen": "serpientestrass",
    "producto": "aplique de serpiente",
    "descripcion": "decoracion  para uña",
    "categoria": "manicura y pedicura",
    "nombreProducto": "aplique de serpiente decoracion  para uña",
    "costo": 200,
    "margenBeneficio": 30,
    "stock": 10,
    "precio": 290,
    "ganancia": 90
  },
  {
    "imagen": "20230103_162815",
    "producto": "mini cambina boom",
    "descripcion": "6w",
    "categoria": "electronico",
    "nombreProducto": "mini cambina boom 6w",
    "costo": 1300,
    "margenBeneficio": 30,
    "stock": 6,
    "precio": 1860,
    "ganancia": 560
  },
  {
    "imagen": "20230425_105924",
    "producto": "cepillo",
    "descripcion": "p/ pestañas 10 u. ",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "cepillo p/ pestañas 10 u. ",
    "costo": 100,
    "margenBeneficio": 45,
    "stock": 20,
    "precio": 180,
    "ganancia": 80
  },
  {
    "imagen": "20230422_105036",
    "producto": "apoya manos ",
    "descripcion": "de madera",
    "categoria": "organizadores",
    "nombreProducto": "apoya manos  de madera",
    "costo": 1500,
    "margenBeneficio": 40,
    "stock": 15,
    "precio": 2500,
    "ganancia": 1000
  },
  {
    "imagen": "20230430_173552",
    "producto": "tips city girls",
    "descripcion": " 240 u flexibles ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "tips city girls  240 u flexibles ",
    "costo": 1400,
    "margenBeneficio": 30,
    "stock": 17,
    "precio": 2000,
    "ganancia": 600
  },
  {
    "imagen": "20230424_161903",
    "producto": "lampara de escritorio",
    "descripcion": "luz blanca",
    "categoria": "electronico",
    "nombreProducto": "lampara de escritorio luz blanca",
    "costo": 2160,
    "margenBeneficio": 35,
    "stock": 2,
    "oferta": 1,
    "precio": 3320,
    "ganancia": 1160
  },
  {
    "imagen": "20230425_121210",
    "producto": "pestañas tipo ramito",
    "descripcion": "x 36 u",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "pestañas tipo ramito x 36 u",
    "costo": 300,
    "margenBeneficio": 50,
    "stock": 6,
    "precio": 600,
    "ganancia": 300
  },
  {
    "imagen": "vkn-77661-824c7c03bc6db6c01516794923718692-640-0",
    "producto": "album p/sticker",
    "descripcion": "entran 80 u",
    "categoria": "organizadores",
    "nombreProducto": "album p/sticker entran 80 u",
    "costo": 700,
    "margenBeneficio": 50,
    "stock": 6,
    "precio": 1400,
    "ganancia": 700
  },
  {
    "imagen": "20230321_190530",
    "producto": "bandeja esterilizadora",
    "descripcion": "color rosa",
    "categoria": "organizadores",
    "nombreProducto": "bandeja esterilizadora color rosa",
    "costo": 2000,
    "margenBeneficio": 35,
    "stock": 1,
    "precio": 3080,
    "ganancia": 1080
  },
  {
    "imagen": "20230203_182359",
    "producto": "esmates charm",
    "descripcion": "reflectivos ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "esmates charm reflectivos ",
    "costo": 560,
    "margenBeneficio": 30,
    "stock": 6,
    "oferta": 1,
    "precio": 800,
    "ganancia": 240
  },
  {
    "imagen": "20230424_161651",
    "producto": "cinta p/ pestaña",
    "descripcion": "hipoaleargenica",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "cinta p/ pestaña hipoaleargenica",
    "costo": 200,
    "margenBeneficio": 40,
    "stock": 0,
    "precio": 330,
    "ganancia": 130
  },
  {
    "imagen": "20230417_094915",
    "producto": "aro luz ",
    "descripcion": "led",
    "categoria": "electronico",
    "nombreProducto": "aro luz  led",
    "costo": 350,
    "margenBeneficio": 50,
    "stock": 2,
    "precio": 700,
    "ganancia": 350
  },
  {
    "imagen": "20230424_154231",
    "producto": "brocha/polvo",
    "descripcion": "color surtido",
    "categoria": "manicura y pedicura",
    "nombreProducto": "brocha/polvo color surtido",
    "costo": 330,
    "margenBeneficio": 40,
    "stock": 10,
    "precio": 550,
    "ganancia": 220
  },
  {
    "imagen": "20230425_105957",
    "producto": "shampo/pestañas",
    "descripcion": "lash original",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "shampo/pestañas lash original",
    "costo": 600,
    "margenBeneficio": 39,
    "stock": 3,
    "precio": 980,
    "ganancia": 380
  },
  {
    "imagen": "20230504_103507",
    "producto": "corta cuticula ",
    "descripcion": "eloise metal",
    "categoria": "manicura y pedicura",
    "nombreProducto": "corta cuticula  eloise metal",
    "costo": 580,
    "margenBeneficio": 40,
    "stock": 5,
    "oferta": 1,
    "precio": 970,
    "ganancia": 390
  },
  {
    "imagen": "20230403_181017",
    "producto": "micro-hisopos",
    "descripcion": " x 50 u surtido",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "micro-hisopos  x 50 u surtido",
    "costo": 400,
    "margenBeneficio": 40,
    "stock": 5,
    "precio": 670,
    "ganancia": 270
  },
  {
    "imagen": "20230320_191707",
    "producto": "linterna chica ",
    "descripcion": "uv color surtido",
    "categoria": "electronico",
    "nombreProducto": "linterna chica  uv color surtido",
    "costo": 700,
    "margenBeneficio": 45,
    "stock": 5,
    "precio": 1270,
    "ganancia": 570
  },
  {
    "imagen": "20230320_192214",
    "producto": "pestaña magnetica",
    "descripcion": "medidas surtidas",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "pestaña magnetica medidas surtidas",
    "costo": 1300,
    "margenBeneficio": 32,
    "stock": 5,
    "precio": 1910,
    "ganancia": 610
  },
  {
    "imagen": "20230320_185642",
    "producto": "cabina-eloise",
    "descripcion": "48w color surtido",
    "categoria": "electronico",
    "nombreProducto": "cabina-eloise 48w color surtido",
    "costo": 4700,
    "margenBeneficio": 40,
    "stock": 4,
    "precio": 6500,
    "ganancia": 1800
  },
  {
    "imagen": "20230424_175101",
    "producto": "polygel navi ",
    "descripcion": "30 ml",
    "categoria": "manicura y pedicura",
    "nombreProducto": "polygel navi  30 ml",
    "costo": 1610,
    "margenBeneficio": 30,
    "stock": 10,
    "oferta": 1,
    "precio": 2300,
    "ganancia": 690
  },
  {
    "imagen": "IMG_20230404_195552_746",
    "producto": "mini palitos",
    "descripcion": "con punta de algodón",
    "categoria": "manicura y pedicura",
    "nombreProducto": "mini palitos con punta de algodón",
    "costo": 180,
    "margenBeneficio": 40,
    "stock": 3,
    "precio": 300,
    "ganancia": 120
  },
  {
    "imagen": "IMG_20230404_195552_928",
    "producto": "pinza lisa",
    "descripcion": "para pestañas",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "pinza lisa para pestañas",
    "costo": 200,
    "margenBeneficio": 60,
    "stock": 4,
    "precio": 500,
    "ganancia": 300
  },
  {
    "imagen": "20230429_101015",
    "producto": "paleta de sombra",
    "descripcion": "x 9 colores",
    "categoria": "maquillaje",
    "nombreProducto": "paleta de sombra x 9 colores",
    "costo": 870,
    "margenBeneficio": 40,
    "stock": 2,
    "precio": 1450,
    "ganancia": 580
  },
  {
    "imagen": "20230429_100954",
    "producto": "base ",
    "descripcion": "fit me 24h",
    "categoria": "maquillaje",
    "nombreProducto": "base  fit me 24h",
    "costo": 400,
    "margenBeneficio": 43,
    "stock": 2,
    "precio": 700,
    "ganancia": 300
  },
  {
    "imagen": "20230429_101055",
    "producto": "paleta de sombra",
    "descripcion": "pink 21 x6",
    "categoria": "maquillaje",
    "nombreProducto": "paleta de sombra pink 21 x6",
    "costo": 580,
    "margenBeneficio": 40,
    "stock": 1,
    "precio": 970,
    "ganancia": 390
  },
  {
    "imagen": "20230429_100828",
    "producto": "mascarilla",
    "descripcion": "puntos p/ negros",
    "categoria": "cuidado personal",
    "nombreProducto": "mascarilla puntos p/ negros",
    "costo": 40,
    "margenBeneficio": 60,
    "stock": 10,
    "precio": 100,
    "ganancia": 60
  },
  {
    "imagen": "20230429_100815",
    "producto": "mascarilla",
    "descripcion": "para rostro natural",
    "categoria": "cuidado personal",
    "nombreProducto": "mascarilla para rostro natural",
    "costo": 200,
    "margenBeneficio": 45,
    "stock": 10,
    "precio": 360,
    "ganancia": 160
  },
  {
    "imagen": "20230426_182328",
    "producto": "apliques cola de sirena",
    "descripcion": "surtido x 1",
    "categoria": "manicura y pedicura",
    "nombreProducto": "apliques cola de sirena surtido x 1",
    "costo": 90,
    "margenBeneficio": 30,
    "stock": 20,
    "precio": 130,
    "ganancia": 40
  },
  {
    "imagen": "c1b7695bae86e0e89ecf5b17caffec7a",
    "producto": "pincel esponja ",
    "descripcion": "surtido x 1",
    "categoria": "manicura y pedicura",
    "nombreProducto": "pincel esponja  surtido x 1",
    "costo": 500,
    "margenBeneficio": 45,
    "stock": 5,
    "precio": 910,
    "ganancia": 410
  },
  {
    "imagen": "20230428_101849",
    "producto": "tips para pies ",
    "descripcion": "x500u",
    "categoria": "manicura y pedicura",
    "nombreProducto": "tips para pies  x500u",
    "costo": 1200,
    "margenBeneficio": 35,
    "stock": 5,
    "precio": 1850,
    "ganancia": 650
  },
  {
    "imagen": "20230426_180348",
    "producto": "plancha de tips city",
    "descripcion": "x24",
    "categoria": "manicura y pedicura",
    "nombreProducto": "plancha de tips city x24",
    "costo": 135,
    "margenBeneficio": 54,
    "stock": 20,
    "precio": 290,
    "ganancia": 155
  },
  {
    "imagen": "20230426_144107",
    "producto": "esmalte semi navi",
    "descripcion": "cover pink",
    "categoria": "manicura y pedicura",
    "nombreProducto": "esmalte semi navi cover pink",
    "costo": 900,
    "margenBeneficio": 38,
    "stock": 6,
    "precio": 1450,
    "ganancia": 550
  },
  {
    "imagen": "20230425_121310",
    "producto": "pestañas pxp",
    "descripcion": "nagaraku color",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "pestañas pxp nagaraku color",
    "costo": 1280,
    "margenBeneficio": 30,
    "stock": 3,
    "precio": 1830,
    "ganancia": 550
  },
  {
    "imagen": "20230424_160301",
    "producto": "polvo efecto power",
    "descripcion": "multicolor paris",
    "categoria": "manicura y pedicura",
    "nombreProducto": "polvo efecto power multicolor paris",
    "costo": 500,
    "margenBeneficio": 35,
    "stock": 3,
    "precio": 770,
    "ganancia": 270
  },
  {
    "imagen": "20230424_160048",
    "producto": "base coat  navi",
    "descripcion": " 10 ml",
    "categoria": "manicura y pedicura",
    "nombreProducto": "base coat  navi  10 ml",
    "costo": 900,
    "margenBeneficio": 40,
    "stock": 5,
    "precio": 1500,
    "ganancia": 600
  },
  {
    "imagen": "20230424_160048",
    "producto": "top coat navi ",
    "descripcion": "10 ml",
    "categoria": "manicura y pedicura",
    "nombreProducto": "top coat navi  10 ml",
    "costo": 900,
    "margenBeneficio": 40,
    "stock": 5,
    "precio": 1500,
    "ganancia": 600
  },
  {
    "imagen": "20230424_160327.",
    "producto": "strass multicoles",
    "descripcion": "carrusel",
    "categoria": "manicura y pedicura",
    "nombreProducto": "strass multicoles carrusel",
    "costo": 240,
    "margenBeneficio": 40,
    "stock": 3,
    "precio": 400,
    "ganancia": 160
  },
  {
    "imagen": "20230424_153715",
    "producto": "strass plateado",
    "descripcion": "1440 pc surtido",
    "categoria": "manicura y pedicura",
    "nombreProducto": "strass plateado 1440 pc surtido",
    "costo": 375,
    "margenBeneficio": 45,
    "stock": 10,
    "precio": 680,
    "ganancia": 305
  },
  {
    "imagen": "20230503_182935",
    "producto": "canasto ",
    "descripcion": "color nude",
    "categoria": "organizadores",
    "nombreProducto": "canasto  color nude",
    "costo": 180,
    "margenBeneficio": 50,
    "stock": 10,
    "precio": 360,
    "ganancia": 180
  },
  {
    "imagen": "20230503_182956",
    "producto": "canasto ",
    "descripcion": "rosa grande ",
    "categoria": "organizadores",
    "nombreProducto": "canasto  rosa grande ",
    "costo": 270,
    "margenBeneficio": 40,
    "stock": 5,
    "precio": 450,
    "ganancia": 180
  },
  {
    "imagen": "20230605_100411",
    "producto": "base cherimoya ",
    "descripcion": "15 ml ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "base cherimoya  15 ml ",
    "costo": 1390,
    "margenBeneficio": 30,
    "stock": 6,
    "oferta": 1,
    "precio": 1990,
    "ganancia": 600
  },
  {
    "imagen": "20230605_100411",
    "producto": "top cherimoya",
    "descripcion": "15 ml",
    "categoria": "manicura y pedicura",
    "nombreProducto": "top cherimoya 15 ml",
    "costo": 1390,
    "margenBeneficio": 30,
    "stock": 10,
    "oferta": 1,
    "precio": 1990,
    "ganancia": 600
  },
  {
    "imagen": "20230503_180914",
    "producto": "ultrabon cherimoya",
    "descripcion": "15 ml ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "ultrabon cherimoya 15 ml ",
    "costo": 1390,
    "margenBeneficio": 30,
    "stock": 0,
    "oferta": 1,
    "precio": 1990,
    "ganancia": 600
  },
  {
    "imagen": "20230503_181315",
    "producto": "charm limit aprobado",
    "descripcion": "base coat",
    "categoria": "manicura y pedicura",
    "nombreProducto": "charm limit aprobado base coat",
    "costo": 650,
    "margenBeneficio": 35,
    "stock": 15,
    "precio": 1000,
    "ganancia": 350
  },
  {
    "imagen": "20230503_181315",
    "producto": "charm limit aprobado",
    "descripcion": "top cristal",
    "categoria": "manicura y pedicura",
    "nombreProducto": "charm limit aprobado top cristal",
    "costo": 650,
    "margenBeneficio": 35,
    "stock": 15,
    "precio": 1000,
    "ganancia": 350
  },
  {
    "imagen": "20230503_181315",
    "producto": "charm limit aprobado",
    "descripcion": "top coat",
    "categoria": "manicura y pedicura",
    "nombreProducto": "charm limit aprobado top coat",
    "costo": 650,
    "margenBeneficio": 35,
    "stock": 15,
    "precio": 1000,
    "ganancia": 350
  },
  {
    "imagen": "20230503_142430",
    "producto": "esmalte semi charm",
    "descripcion": " 9 ml consultar",
    "categoria": "manicura y pedicura",
    "nombreProducto": "esmalte semi charm 9 ml consultar",
    "costo": 300,
    "margenBeneficio": 30,
    "stock": 20,
    "precio": 430,
    "ganancia": 130
  },
  {
    "imagen": "20230503_130240",
    "producto": "esmalte semi charm",
    "descripcion": "10 ml",
    "categoria": "manicura y pedicura",
    "nombreProducto": "esmalte semi charm10 ml",
    "costo": 350,
    "margenBeneficio": 30,
    "stock": 90,
    "precio": 500,
    "ganancia": 150
  },
  {
    "imagen": "20230503_125108",
    "producto": "picel liner  ",
    "descripcion": "x3",
    "categoria": "manicura y pedicura",
    "nombreProducto": "picel liner  x3",
    "costo": 270,
    "margenBeneficio": 42,
    "stock": 5,
    "precio": 470,
    "ganancia": 200
  },
  {
    "imagen": "20230502_135552",
    "producto": "sanitizante lfme",
    "descripcion": "120 ml",
    "categoria": "manicura y pedicura",
    "nombreProducto": "sanitizante lfme120 ml",
    "costo": 320,
    "margenBeneficio": 45,
    "stock": 10,
    "precio": 580,
    "ganancia": 260
  },
  {
    "imagen": "20230502_134925",
    "producto": "pegamento nagaraku ",
    "descripcion": "clear ",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "pegamento nagaraku clear ",
    "costo": 2100,
    "margenBeneficio": 37,
    "stock": 4,
    "precio": 3330,
    "ganancia": 1230
  },
  {
    "imagen": "20230502_131529",
    "producto": "pincel lengua de gato",
    "descripcion": "  n8",
    "categoria": "manicura y pedicura",
    "nombreProducto": "pincel lengua de gato  n8",
    "costo": 270,
    "margenBeneficio": 30,
    "stock": 10,
    "precio": 390,
    "ganancia": 120
  },
  {
    "imagen": "20230502_131419",
    "producto": "pincel para gel",
    "descripcion": " n 8",
    "categoria": "manicura y pedicura",
    "nombreProducto": "pincel para gel n 8",
    "costo": 250,
    "margenBeneficio": 30,
    "stock": 1,
    "precio": 360,
    "ganancia": 110
  },
  {
    "imagen": "20230502_131354",
    "producto": "pincel para esculpida",
    "descripcion": " n 8",
    "categoria": "manicura y pedicura",
    "nombreProducto": "pincel para esculpida n 8",
    "costo": 250,
    "margenBeneficio": 30,
    "stock": 5,
    "precio": 360,
    "ganancia": 110
  },
  {
    "imagen": "20230424_155132",
    "producto": "aceite cherimoya",
    "descripcion": " premiun",
    "categoria": "manicura y pedicura",
    "nombreProducto": "aceite cherimoya premiun",
    "costo": 350,
    "margenBeneficio": 40,
    "stock": 5,
    "precio": 580,
    "ganancia": 230
  },
  {
    "imagen": "20230424_154859",
    "producto": "primer las varanos",
    "descripcion": " con o sin acido",
    "categoria": "manicura y pedicura",
    "nombreProducto": "primer las varanos con o sin acido",
    "costo": 380,
    "margenBeneficio": 35,
    "stock": 10,
    "precio": 580,
    "ganancia": 200
  },
  {
    "imagen": "20230424_155206.",
    "producto": "polimero qbd ",
    "descripcion": "30 gr",
    "categoria": "manicura y pedicura",
    "nombreProducto": "polimero qbd 30 gr",
    "costo": 430,
    "margenBeneficio": 45,
    "stock": 10,
    "precio": 780,
    "ganancia": 350
  },
  {
    "imagen": "20230414_094753",
    "producto": "compresas x 10",
    "descripcion": " color surtido",
    "categoria": "manicura y pedicura",
    "nombreProducto": "compresas x 10 color surtido",
    "costo": 580,
    "margenBeneficio": 30,
    "stock": 10,
    "precio": 830,
    "ganancia": 250
  },
  {
    "imagen": "20230414_101844",
    "producto": "pinturas tei",
    "descripcion": " 10 ml consultar color",
    "categoria": "manicura y pedicura",
    "nombreProducto": "pinturas tei 10 ml consultar color",
    "costo": 300,
    "margenBeneficio": 33,
    "stock": 25,
    "precio": 450,
    "ganancia": 150
  },
  {
    "imagen": "20230424_155254",
    "producto": " cintas deco",
    "descripcion": "varios colores",
    "categoria": "manicura y pedicura",
    "nombreProducto": " cintas decovarios colores",
    "costo": 40,
    "margenBeneficio": 45,
    "stock": 10,
    "precio": 70,
    "ganancia": 30
  },
  {
    "imagen": "20230424_155340",
    "producto": "perfec liner",
    "descripcion": " universal",
    "categoria": "manicura y pedicura",
    "nombreProducto": "perfec liner universal",
    "costo": 190,
    "margenBeneficio": 40,
    "stock": 4,
    "precio": 320,
    "ganancia": 130
  },
  {
    "imagen": "20230424_155358",
    "producto": "pega foil",
    "descripcion": " las varanos",
    "categoria": "manicura y pedicura",
    "nombreProducto": "pega foil las varanos",
    "costo": 200,
    "margenBeneficio": 55,
    "stock": 4,
    "precio": 440,
    "ganancia": 240
  },
  {
    "imagen": "20230424_155905",
    "producto": "fesa ",
    "descripcion": "pulidora",
    "categoria": "manicura y pedicura",
    "nombreProducto": "fesa pulidora",
    "costo": 200,
    "margenBeneficio": 50,
    "stock": 9,
    "precio": 400,
    "ganancia": 200
  },
  {
    "imagen": "20230504_103641",
    "producto": "tijera curva",
    "descripcion": "eloise metal",
    "categoria": "manicura y pedicura",
    "nombreProducto": "tijera curvaeloise metal",
    "costo": 220,
    "margenBeneficio": 54,
    "stock": 10,
    "precio": 480,
    "ganancia": 260
  },
  {
    "imagen": "20230504_134729",
    "producto": "cabina con soporte",
    "descripcion": " 48 w",
    "categoria": "manicura y pedicura",
    "nombreProducto": "cabina con soporte 48 w",
    "costo": 5500,
    "margenBeneficio": 33,
    "stock": 0,
    "precio": 8210,
    "ganancia": 2710
  },
  {
    "imagen": "20230424_153615",
    "producto": "set liner x 3",
    "descripcion": "brillo",
    "categoria": "manicura y pedicura",
    "nombreProducto": "set liner x 3brillo",
    "costo": 500,
    "margenBeneficio": 35,
    "stock": 10,
    "precio": 770,
    "ganancia": 270
  },
  {
    "imagen": "20230414_135631",
    "producto": "pegamento nagaraku ",
    "descripcion": "blanco o negro",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "pegamento nagaraku blanco o negro",
    "costo": 2200,
    "margenBeneficio": 32,
    "stock": 6,
    "precio": 3240,
    "ganancia": 1040
  },
  {
    "imagen": "20230414_121654",
    "producto": "barbijos x 10",
    "descripcion": " consultar color",
    "categoria": "manicura y pedicura",
    "nombreProducto": "barbijos x 10 consultar color",
    "costo": 100,
    "margenBeneficio": 50,
    "stock": 10,
    "precio": 200,
    "ganancia": 100
  },
  {
    "imagen": "20220810_195445",
    "producto": "set de fresas",
    "descripcion": "x 4 ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "set de fresasx 4 ",
    "costo": 680,
    "margenBeneficio": 40,
    "stock": 3,
    "precio": 1130,
    "ganancia": 450
  },
  {
    "imagen": "20220810_193853",
    "producto": "sello stamping ",
    "descripcion": "color surtido",
    "categoria": "manicura y pedicura",
    "nombreProducto": "sello stamping color surtido",
    "costo": 780,
    "margenBeneficio": 30,
    "stock": 3,
    "precio": 1110,
    "ganancia": 330
  },
  {
    "imagen": "20220810_193937",
    "producto": "kapping gel cherimoya",
    "descripcion": " consultar color",
    "categoria": "manicura y pedicura",
    "nombreProducto": "kapping gel cherimoya consultar color",
    "costo": 1200,
    "margenBeneficio": 40,
    "stock": 0,
    "precio": 2000,
    "ganancia": 800
  },
  {
    "imagen": "20220829_101440",
    "producto": "gel solido cherimoya ",
    "descripcion": "10 gr",
    "categoria": "manicura y pedicura",
    "nombreProducto": "gel solido cherimoya 10 gr",
    "costo": 1100,
    "margenBeneficio": 32,
    "stock": 10,
    "precio": 1620,
    "ganancia": 520
  },
  {
    "imagen": "20220820_205205-1",
    "producto": "gel paint ",
    "descripcion": "negro o blanco",
    "categoria": "manicura y pedicura",
    "nombreProducto": "gel paint negro o blanco",
    "costo": 180,
    "margenBeneficio": 35,
    "stock": 10,
    "precio": 280,
    "ganancia": 100
  },
  {
    "imagen": "20220829_113637",
    "producto": "gel de contruccion lina",
    "descripcion": " consultar color",
    "categoria": "manicura y pedicura",
    "nombreProducto": "gel de contruccion lina consultar color",
    "costo": 400,
    "margenBeneficio": 33,
    "stock": 10,
    "precio": 600,
    "ganancia": 200
  },
  {
    "imagen": "20230517_111316",
    "producto": "gel de contruccion charm litm",
    "descripcion": "15 ml",
    "categoria": "manicura y pedicura",
    "nombreProducto": "gel de contruccion charm litm15 ml",
    "costo": 790,
    "margenBeneficio": 35,
    "stock": 9,
    "precio": 1220,
    "ganancia": 430
  },
  {
    "imagen": "20220830_112822",
    "producto": "primer lfme ",
    "descripcion": "sin acido",
    "categoria": "manicura y pedicura",
    "nombreProducto": "primer lfme sin acido",
    "costo": 300,
    "margenBeneficio": 40,
    "stock": 8,
    "precio": 500,
    "ganancia": 200
  },
  {
    "imagen": "20220830_103412",
    "producto": "zanitizante",
    "descripcion": " las varanos 120 ml",
    "categoria": "manicura y pedicura",
    "nombreProducto": "zanitizante las varanos 120 ml",
    "costo": 480,
    "margenBeneficio": 35,
    "stock": 3,
    "precio": 740,
    "ganancia": 260
  },
  {
    "imagen": "20220829_113637",
    "producto": "gel de contruccion tina",
    "descripcion": " consultar color",
    "categoria": "manicura y pedicura",
    "nombreProducto": "gel de contruccion tina consultar color",
    "costo": 380,
    "margenBeneficio": 35,
    "stock": 10,
    "precio": 580,
    "ganancia": 200
  },
  {
    "imagen": "20220820_205205-1.",
    "producto": "gel paint ",
    "descripcion": "negro o blanco",
    "categoria": "manicura y pedicura",
    "nombreProducto": "gel paint negro o blanco",
    "costo": 140,
    "margenBeneficio": 50,
    "stock": 6,
    "precio": 280,
    "ganancia": 140
  },
  {
    "imagen": "20220830_112822",
    "producto": "primer con acido lfme",
    "descripcion": "11 ml",
    "categoria": "manicura y pedicura",
    "nombreProducto": "primer con acido lfme11 ml",
    "costo": 300,
    "margenBeneficio": 37,
    "stock": 0,
    "precio": 480,
    "ganancia": 180
  },
  {
    "imagen": "20230503_180914",
    "producto": "ph balancing cherimoya ",
    "descripcion": " tapa blanca",
    "categoria": "manicura y pedicura",
    "nombreProducto": "ph balancing cherimoya  tapa blanca",
    "costo": 1350,
    "margenBeneficio": 32,
    "stock": 6,
    "precio": 1990,
    "ganancia": 640
  },
  {
    "imagen": "20230503_180914",
    "producto": "primer cherimoya ",
    "descripcion": "tapa blanca",
    "categoria": "manicura y pedicura",
    "nombreProducto": "primer cherimoya tapa blanca",
    "costo": 1350,
    "margenBeneficio": 32,
    "stock": 3,
    "precio": 1990,
    "ganancia": 640
  },
  {
    "imagen": "20230515_004339",
    "producto": "iman doble",
    "descripcion": "color gris",
    "categoria": "manicura y pedicura",
    "nombreProducto": "iman doblecolor gris",
    "costo": 480,
    "margenBeneficio": 40,
    "stock": 3,
    "precio": 800,
    "ganancia": 320
  },
  {
    "imagen": "20230515_004436",
    "producto": " set x 3 pincel",
    "descripcion": "almendra sirena",
    "categoria": "manicura y pedicura",
    "nombreProducto": " set x 3 pincelalmendra sirena",
    "costo": 570,
    "margenBeneficio": 40,
    "stock": 3,
    "precio": 950,
    "ganancia": 380
  },
  {
    "imagen": "20230515_004514",
    "producto": "pincel mini abanico",
    "descripcion": " mango madera ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "pincel mini abanico mango madera ",
    "costo": 240,
    "margenBeneficio": 40,
    "stock": 10,
    "precio": 400,
    "ganancia": 160
  },
  {
    "imagen": "20230515_004554",
    "producto": "pincel liner eloise ",
    "descripcion": " strass ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "pincel liner eloise  strass ",
    "costo": 400,
    "margenBeneficio": 40,
    "stock": 2,
    "precio": 670,
    "ganancia": 270
  },
  {
    "imagen": "20230515_004845",
    "producto": "pincel de goma",
    "descripcion": " x1 mango madera",
    "categoria": "manicura y pedicura",
    "nombreProducto": "pincel de goma x1 mango madera",
    "costo": 130,
    "margenBeneficio": 40,
    "stock": 10,
    "precio": 220,
    "ganancia": 90
  },
  {
    "imagen": "20230515_005057",
    "producto": "set de muestrario ",
    "descripcion": "x 50 u cuadrado",
    "categoria": "manicura y pedicura",
    "nombreProducto": "set de muestrario x 50 u cuadrado",
    "costo": 470,
    "margenBeneficio": 40,
    "stock": 6,
    "precio": 780,
    "ganancia": 310
  },
  {
    "imagen": "20230515_005522",
    "producto": "set muestrario",
    "descripcion": " x50 u stiletto",
    "categoria": "manicura y pedicura",
    "nombreProducto": "set muestrario x50 u stiletto",
    "costo": 470,
    "margenBeneficio": 40,
    "stock": 5,
    "precio": 780,
    "ganancia": 310
  },
  {
    "imagen": "20230515_010941",
    "producto": "dedo de practica  ",
    "descripcion": "sin o con uña",
    "categoria": "manicura y pedicura",
    "nombreProducto": "dedo de practica  sin o con uña",
    "costo": 100,
    "margenBeneficio": 40,
    "stock": 7,
    "precio": 170,
    "ganancia": 70
  },
  {
    "imagen": "20230515_011004",
    "producto": "remodedor en gel",
    "descripcion": " las varanos ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "remodedor en gel las varanos ",
    "costo": 270,
    "margenBeneficio": 40,
    "stock": 10,
    "precio": 450,
    "ganancia": 180
  },
  {
    "imagen": "20230515_002717",
    "producto": "mini cabina boom ",
    "descripcion": "abierto paris night",
    "categoria": "manicura y pedicura",
    "nombreProducto": "mini cabina boom abierto paris night",
    "costo": 1650,
    "margenBeneficio": 40,
    "stock": 4,
    "precio": 2750,
    "ganancia": 1100
  },
  {
    "imagen": "20230515_002909",
    "producto": "parche de pestañas ",
    "descripcion": " x 10 u",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "parche de pestañas  x 10 u",
    "costo": 100,
    "margenBeneficio": 49,
    "stock": 15,
    "precio": 200,
    "ganancia": 100
  },
  {
    "imagen": "20230515_003037",
    "producto": "palito de naranjo ",
    "descripcion": " x 10 u acrilico",
    "categoria": "manicura y pedicura",
    "nombreProducto": "palito de naranjo  x 10 u acrilico",
    "costo": 60,
    "margenBeneficio": 69,
    "stock": 20,
    "precio": 190,
    "ganancia": 130
  },
  {
    "imagen": "20230515_003145",
    "producto": "top coat cham ",
    "descripcion": "tapa negra",
    "categoria": "manicura y pedicura",
    "nombreProducto": "top coat cham tapa negra",
    "costo": 440,
    "margenBeneficio": 40,
    "stock": 8,
    "oferta": 1,
    "precio": 730,
    "ganancia": 290
  },
  {
    "imagen": "20230515_003145",
    "producto": "base coat charm ",
    "descripcion": "tapa negra",
    "categoria": "manicura y pedicura",
    "nombreProducto": "base coat charm tapa negra",
    "costo": 440,
    "margenBeneficio": 35,
    "stock": 10,
    "oferta": 1,
    "precio": 680,
    "ganancia": 240
  },
  {
    "imagen": "20230515_003145",
    "producto": "top coat cristal",
    "descripcion": "tapa negra",
    "categoria": "manicura y pedicura",
    "nombreProducto": "top coat cristaltapa negra",
    "costo": 440,
    "margenBeneficio": 35,
    "stock": 10,
    "oferta": 1,
    "precio": 680,
    "ganancia": 240
  },
  {
    "imagen": "20230515_003705",
    "producto": "apoya tips city girls",
    "descripcion": " color surtido",
    "categoria": "manicura y pedicura",
    "nombreProducto": "apoya tips city girls color surtido",
    "costo": 500,
    "margenBeneficio": 48,
    "stock": 5,
    "precio": 960,
    "ganancia": 460
  },
  {
    "imagen": "20230515_004144",
    "producto": "organizador de pestañas ",
    "descripcion": "para la muñeca acrilico ",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "organizador de pestañas para la muñeca acrilico ",
    "costo": 540,
    "margenBeneficio": 40,
    "stock": 3,
    "precio": 900,
    "ganancia": 360
  },
  {
    "imagen": "20230515_004239",
    "producto": "cinta bifas ",
    "descripcion": "transparente ",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "cinta bifas transparente ",
    "costo": 150,
    "margenBeneficio": 40,
    "stock": 9,
    "precio": 250,
    "ganancia": 100
  },
  {
    "imagen": "20230515_003922",
    "producto": "pestañas nagaraku",
    "descripcion": "linea elipse ",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "pestañas nagarakulinea elipse ",
    "costo": 1600,
    "margenBeneficio": 31,
    "stock": 4,
    "oferta": 1,
    "precio": 2320,
    "ganancia": 720
  },
  {
    "imagen": "20230513_162234",
    "producto": "polvo holografico ",
    "descripcion": "paris nigt",
    "categoria": "manicura y pedicura",
    "nombreProducto": "polvo holografico paris nigt",
    "costo": 540,
    "margenBeneficio": 30,
    "stock": 2,
    "precio": 770,
    "ganancia": 230
  },
  {
    "imagen": "20230513_162355",
    "producto": " polvo aurora",
    "descripcion": "paris nigt",
    "categoria": "manicura y pedicura",
    "nombreProducto": " polvo auroraparis nigt",
    "costo": 500,
    "margenBeneficio": 30,
    "stock": 3,
    "precio": 710,
    "ganancia": 210
  },
  {
    "imagen": "20230513_161421",
    "producto": "apliques de corazon",
    "descripcion": "x 5 uni",
    "categoria": "manicura y pedicura",
    "nombreProducto": "apliques de corazonx 5 uni",
    "costo": 150,
    "margenBeneficio": 30,
    "stock": 4,
    "precio": 210,
    "ganancia": 60
  },
  {
    "imagen": "20230513_161305",
    "producto": "cola de sirena ",
    "descripcion": "por potecito",
    "categoria": "manicura y pedicura",
    "nombreProducto": "cola de sirena por potecito",
    "costo": 100,
    "margenBeneficio": 30,
    "stock": 25,
    "precio": 140,
    "ganancia": 40
  },
  {
    "imagen": "20230513_161148",
    "producto": "henna para cejas",
    "descripcion": "consultar color",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "henna para cejasconsultar color",
    "costo": 1900,
    "margenBeneficio": 35,
    "stock": 2,
    "precio": 2920,
    "ganancia": 1020
  },
  {
    "imagen": "20230513_161120",
    "producto": "moldes dorados ",
    "descripcion": " x100 u",
    "categoria": "manicura y pedicura",
    "nombreProducto": "moldes dorados  x100 u",
    "costo": 240,
    "margenBeneficio": 40,
    "stock": 10,
    "precio": 400,
    "ganancia": 160
  },
  {
    "imagen": "20230513_145601",
    "producto": "marcador de acrilico",
    "descripcion": " plata/oro",
    "categoria": "manicura y pedicura",
    "nombreProducto": "marcador de acrilico plata/oro",
    "costo": 800,
    "margenBeneficio": 35,
    "stock": 6,
    "precio": 1230,
    "ganancia": 430
  },
  {
    "imagen": "20230513_145219",
    "producto": "capsula para polygel",
    "descripcion": "city girls coffin",
    "categoria": "manicura y pedicura",
    "nombreProducto": "capsula para polygelcity girls coffin",
    "costo": 1000,
    "margenBeneficio": 35,
    "stock": 5,
    "precio": 1540,
    "ganancia": 540
  },
  {
    "imagen": "20230513_145046",
    "producto": "apliques de flores",
    "descripcion": "color surtido",
    "categoria": "manicura y pedicura",
    "nombreProducto": "apliques de florescolor surtido",
    "costo": 250,
    "margenBeneficio": 48,
    "stock": 8,
    "precio": 480,
    "ganancia": 230
  },
  {
    "imagen": "20230513_144727",
    "producto": "piercing para uñas",
    "descripcion": "dorado/plata",
    "categoria": "manicura y pedicura",
    "nombreProducto": "piercing para uñasdorado/plata",
    "costo": 140,
    "margenBeneficio": 49,
    "stock": 5,
    "precio": 270,
    "ganancia": 130
  },
  {
    "imagen": "20230513_144647",
    "producto": "polvo brilloso",
    "descripcion": "color sutido",
    "categoria": "manicura y pedicura",
    "nombreProducto": "polvo brillosocolor sutido",
    "costo": 260,
    "margenBeneficio": 40,
    "stock": 3,
    "precio": 430,
    "ganancia": 170
  },
  {
    "imagen": "20230515_134245",
    "producto": "tips eloise ",
    "descripcion": " x100 u transparente coffin",
    "categoria": "manicura y pedicura",
    "nombreProducto": "tips eloise  x100 u transparente coffin",
    "costo": 650,
    "margenBeneficio": 31,
    "stock": 10,
    "precio": 940,
    "ganancia": 290
  },
  {
    "imagen": "20230515_134321",
    "producto": "tips eloise ",
    "descripcion": "x100 u tranparente almendra",
    "categoria": "manicura y pedicura",
    "nombreProducto": "tips eloise x100 u tranparente almendra",
    "costo": 650,
    "margenBeneficio": 31,
    "stock": 10,
    "precio": 940,
    "ganancia": 290
  },
  {
    "imagen": "20230515_012915",
    "producto": "mini cabina sun",
    "descripcion": "24 w",
    "categoria": "electronico",
    "nombreProducto": "mini cabina sun24 w",
    "costo": 800,
    "margenBeneficio": 40,
    "stock": 5,
    "precio": 1330,
    "ganancia": 530
  },
  {
    "imagen": "20230517_105808",
    "producto": "polvo espejo ",
    "descripcion": "colores surtido",
    "categoria": "manicura y pedicura",
    "nombreProducto": "polvo espejo colores surtido",
    "costo": 240,
    "margenBeneficio": 58,
    "stock": 23,
    "precio": 570,
    "ganancia": 330
  },
  {
    "imagen": "20230517_114728",
    "producto": "strass city girls ",
    "descripcion": "1440 pc surtido",
    "categoria": "manicura y pedicura",
    "nombreProducto": "strass city girls 1440 pc surtido",
    "costo": 490,
    "margenBeneficio": 37,
    "stock": 5,
    "precio": 780,
    "ganancia": 290
  },
  {
    "imagen": "20230517_114822",
    "producto": "strass diamante ",
    "descripcion": "colores surtido",
    "categoria": "manicura y pedicura",
    "nombreProducto": "strass diamante colores surtido",
    "costo": 300,
    "margenBeneficio": 47,
    "stock": 5,
    "precio": 570,
    "ganancia": 270
  },
  {
    "imagen": "20230517_114831",
    "producto": "strass color eco",
    "descripcion": "surtido x 1",
    "categoria": "manicura y pedicura",
    "nombreProducto": "strass color ecosurtido x 1",
    "costo": 300,
    "margenBeneficio": 48,
    "stock": 3,
    "precio": 580,
    "ganancia": 280
  },
  {
    "imagen": "20230517_114350",
    "producto": "aplique pompom corazon",
    "descripcion": "x 12",
    "categoria": "manicura y pedicura",
    "nombreProducto": "aplique pompom corazonx 12",
    "costo": 650,
    "margenBeneficio": 50,
    "stock": 2,
    "precio": 1300,
    "ganancia": 650
  },
  {
    "imagen": "20230517_114229",
    "producto": "aplique de mariposa con iman",
    "descripcion": " x 6  ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "aplique de mariposa con iman x 6  ",
    "costo": 600,
    "margenBeneficio": 50,
    "stock": 2,
    "precio": 1200,
    "ganancia": 600
  },
  {
    "imagen": "20230517_111942",
    "producto": "apliques tiernos ",
    "descripcion": "x 12",
    "categoria": "manicura y pedicura",
    "nombreProducto": "apliques tiernos x 12",
    "costo": 500,
    "margenBeneficio": 38,
    "stock": 3,
    "precio": 810,
    "ganancia": 310
  },
  {
    "imagen": "20230517_111654",
    "producto": "apliques golosina ",
    "descripcion": " surtido",
    "categoria": "manicura y pedicura",
    "nombreProducto": "apliques golosina  surtido",
    "costo": 380,
    "margenBeneficio": 44,
    "stock": 4,
    "precio": 680,
    "ganancia": 300
  },
  {
    "imagen": "20230517_111326",
    "producto": "base corectiva eloise ",
    "descripcion": "color rosa",
    "categoria": "manicura y pedicura",
    "nombreProducto": "base corectiva eloise color rosa",
    "costo": 800,
    "margenBeneficio": 35,
    "stock": 2,
    "precio": 1230,
    "ganancia": 430
  },
  {
    "imagen": "20230517_111243",
    "producto": "kapping chamr limit",
    "descripcion": " transparente ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "kapping chamr limit transparente ",
    "costo": 700,
    "margenBeneficio": 35,
    "stock": 4,
    "precio": 1080,
    "ganancia": 380
  },
  {
    "imagen": "20230517_111234",
    "producto": "kapping transferir reloise ",
    "descripcion": "transparente ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "kapping transferir reloise transparente ",
    "costo": 680,
    "margenBeneficio": 40,
    "stock": 1,
    "precio": 1130,
    "ganancia": 450
  },
  {
    "imagen": "20230517_110905",
    "producto": "lima nails sunshine",
    "descripcion": "240/180",
    "categoria": "manicura y pedicura",
    "nombreProducto": "lima nails sunshine240/180",
    "costo": 150,
    "margenBeneficio": 38,
    "stock": 13,
    "precio": 240,
    "ganancia": 90
  },
  {
    "imagen": "20230517_110839",
    "producto": "lima city girls",
    "descripcion": "150/150",
    "categoria": "manicura y pedicura",
    "nombreProducto": "lima city girls150/150",
    "costo": 150,
    "margenBeneficio": 38,
    "stock": 13,
    "precio": 240,
    "ganancia": 90
  },
  {
    "imagen": "20230517_110824",
    "producto": "lima nails sunshine",
    "descripcion": " 240/240",
    "categoria": "manicura y pedicura",
    "nombreProducto": "lima nails sunshine 240/240",
    "costo": 150,
    "margenBeneficio": 38,
    "stock": 16,
    "precio": 240,
    "ganancia": 90
  },
  {
    "imagen": "20230517_110831",
    "producto": "lima Paris Night",
    "descripcion": " 100/180",
    "categoria": "manicura y pedicura",
    "nombreProducto": "lima Paris Night 100/180",
    "costo": 240,
    "margenBeneficio": 30,
    "stock": 18,
    "precio": 340,
    "ganancia": 100
  },
  {
    "imagen": "20230517_110811",
    "producto": "lima sk ",
    "descripcion": "100/180",
    "categoria": "manicura y pedicura",
    "nombreProducto": "lima sk 100/180",
    "costo": 150,
    "margenBeneficio": 36,
    "stock": 34,
    "precio": 230,
    "ganancia": 80
  },
  {
    "imagen": "20230517_110803",
    "producto": "lima opi ",
    "descripcion": "100/180",
    "categoria": "manicura y pedicura",
    "nombreProducto": "lima opi 100/180",
    "costo": 80,
    "margenBeneficio": 35,
    "stock": 20,
    "precio": 120,
    "ganancia": 40
  },
  {
    "imagen": "20230517_110755",
    "producto": "lima cherimoya ",
    "descripcion": "100/180",
    "categoria": "manicura y pedicura",
    "nombreProducto": "lima cherimoya 100/180",
    "costo": 150,
    "margenBeneficio": 42,
    "stock": 2,
    "precio": 260,
    "ganancia": 110
  },
  {
    "imagen": "20230517_110747",
    "producto": "lima sunshine ",
    "descripcion": "150/150",
    "categoria": "manicura y pedicura",
    "nombreProducto": "lima sunshine 150/150",
    "costo": 140,
    "margenBeneficio": 39,
    "stock": 6,
    "precio": 230,
    "ganancia": 90
  },
  {
    "imagen": "20230517_110732",
    "producto": "lima sunshine ",
    "descripcion": " 100/100",
    "categoria": "manicura y pedicura",
    "nombreProducto": "lima sunshine  100/100",
    "costo": 140,
    "margenBeneficio": 39,
    "stock": 5,
    "precio": 230,
    "ganancia": 90
  },
  {
    "imagen": "20230517_110701",
    "producto": "lima sunshine ",
    "descripcion": " 180/180",
    "categoria": "manicura y pedicura",
    "nombreProducto": "lima sunshine  180/180",
    "costo": 140,
    "margenBeneficio": 39,
    "stock": 7,
    "precio": 230,
    "ganancia": 90
  },
  {
    "imagen": "20230517_110453",
    "producto": "set de fresas ",
    "descripcion": " x 6  ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "set de fresas  x 6  ",
    "costo": 450,
    "margenBeneficio": 40,
    "stock": 2,
    "precio": 750,
    "ganancia": 300
  },
  {
    "imagen": "20230517_110424",
    "producto": "gel paint navi",
    "descripcion": " negro o blanco",
    "categoria": "manicura y pedicura",
    "nombreProducto": "gel paint navi negro o blanco",
    "costo": 1700,
    "margenBeneficio": 30,
    "stock": 2,
    "precio": 2430,
    "ganancia": 730
  },
  {
    "imagen": "20230513_144325",
    "producto": "strass bolsita ",
    "descripcion": "multicolor ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "strass bolsita multicolor ",
    "costo": 350,
    "margenBeneficio": 30,
    "stock": 10,
    "precio": 500,
    "ganancia": 150
  },
  {
    "imagen": "20230513_124423",
    "producto": "monomero ezflow",
    "descripcion": "120 ml ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "monomero ezflow120 ml ",
    "costo": 1500,
    "margenBeneficio": 30,
    "stock": 8,
    "precio": 2140,
    "ganancia": 640
  },
  {
    "imagen": "20230511_184200",
    "producto": "lapiz de cera levanta strass",
    "descripcion": "x1",
    "categoria": "manicura y pedicura",
    "nombreProducto": "lapiz de cera levanta strassx1",
    "costo": 170,
    "margenBeneficio": 35,
    "stock": 5,
    "precio": 260,
    "ganancia": 90
  },
  {
    "imagen": "20230511_184042",
    "producto": "pincel para poligel c/ espatula",
    "descripcion": "rosa o negro",
    "categoria": "manicura y pedicura",
    "nombreProducto": "pincel para poligel c/ espatularosa o negro",
    "costo": 600,
    "margenBeneficio": 37,
    "stock": 14,
    "precio": 950,
    "ganancia": 350
  },
  {
    "imagen": "20230511_183935",
    "producto": "pestaña pxp ",
    "descripcion": "7d 13,14,15",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "pestaña pxp 7d 13,14,15",
    "costo": 1450,
    "margenBeneficio": 30,
    "stock": 20,
    "precio": 2070,
    "ganancia": 620
  },
  {
    "imagen": "20230511_183726",
    "producto": "moldes eloise rosa",
    "descripcion": " x30 u ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "moldes eloise rosa x30 u ",
    "costo": 290,
    "margenBeneficio": 40,
    "stock": 30,
    "precio": 480,
    "ganancia": 190
  },
  {
    "imagen": "20230511_183322",
    "producto": "moldes cherimoya",
    "descripcion": " x 30",
    "categoria": "manicura y pedicura",
    "nombreProducto": "moldes cherimoya x 30",
    "costo": 260,
    "margenBeneficio": 47,
    "stock": 14,
    "precio": 490,
    "ganancia": 230
  },
  {
    "imagen": "20230523_135822",
    "producto": "mini lima esponge",
    "descripcion": "x 1 ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "mini lima  esponje x 1 u",
    "costo": 50,
    "margenBeneficio": 35,
    "stock": 20,
    "precio": 80,
    "ganancia": 30
  },
  {
    "imagen": "20230523_133657",
    "producto": "palito de naranjo ",
    "descripcion": " x12 u de madera",
    "categoria": "manicura y pedicura",
    "nombreProducto": "palito de naranjo  x12 u de madera",
    "costo": 75,
    "margenBeneficio": 50,
    "stock": 16,
    "precio": 150,
    "ganancia": 75
  },
  {
    "imagen": "20230523_133356",
    "producto": "corta tips ",
    "descripcion": "de metal color rosa",
    "categoria": "manicura y pedicura",
    "nombreProducto": "corta tips de metal color rosa",
    "costo": 480,
    "margenBeneficio": 40,
    "stock": 5,
    "precio": 800,
    "ganancia": 320
  },
  {
    "imagen": "20230523_133316",
    "producto": "pestañas x ramito",
    "descripcion": "c/ rosa",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "pestañas x ramitoc/ rosa",
    "costo": 380,
    "margenBeneficio": 37,
    "stock": 6,
    "precio": 600,
    "ganancia": 220
  },
  {
    "imagen": "20230523_133153",
    "producto": "plancha de adhesivos ",
    "descripcion": "x 2",
    "categoria": "manicura y pedicura",
    "nombreProducto": "plancha de adhesivos x 2",
    "costo": 100,
    "margenBeneficio": 35,
    "stock": 7,
    "precio": 150,
    "ganancia": 50
  },
  {
    "imagen": "20230523_133110",
    "producto": "limas por bolsitas ",
    "descripcion": "rosas x 12 u",
    "categoria": "manicura y pedicura",
    "nombreProducto": "limas por bolsitas rosas x 12 u",
    "costo": 350,
    "margenBeneficio": 40,
    "stock": 4,
    "precio": 580,
    "ganancia": 230
  },
  {
    "imagen": "20230523_133028",
    "producto": "escofina de metal ",
    "descripcion": "color surtido",
    "categoria": "manicura y pedicura",
    "nombreProducto": "escofina de metal color surtido",
    "costo": 380,
    "margenBeneficio": 30,
    "stock": 3,
    "precio": 540,
    "ganancia": 160
  },
  {
    "imagen": "20230523_132925",
    "producto": "quita callos + corta cuticula",
    "descripcion": " color surtidos",
    "categoria": "manicura y pedicura",
    "nombreProducto": "quita callos + corta cuticula color surtidos",
    "costo": 280,
    "margenBeneficio": 40,
    "stock": 3,
    "precio": 470,
    "ganancia": 190
  },
  {
    "imagen": "20230523_132825",
    "producto": "removedor uv lfme",
    "descripcion": "120 ml",
    "categoria": "manicura y pedicura",
    "nombreProducto": "removedor uv lfme120 ml",
    "costo": 400,
    "margenBeneficio": 33,
    "stock": 10,
    "precio": 600,
    "ganancia": 200
  },
  {
    "imagen": "20230523_132811",
    "producto": "clarificador las varanos ",
    "descripcion": "125 ml",
    "categoria": "manicura y pedicura",
    "nombreProducto": "clarificador las varanos 125 ml",
    "costo": 500,
    "margenBeneficio": 30,
    "stock": 3,
    "precio": 710,
    "ganancia": 210
  },
  {
    "imagen": "20230519_115334",
    "producto": "esmalte uv huevo de cordoniz",
    "descripcion": " 10 ml",
    "categoria": "manicura y pedicura",
    "nombreProducto": "esmalte uv huevo de cordoniz 10 ml",
    "costo": 450,
    "margenBeneficio": 40,
    "stock": 4,
    "precio": 750,
    "ganancia": 300
  },
  {
    "imagen": "20230519_113626",
    "producto": "aceite de cuticula ",
    "descripcion": "artesanal ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "aceite de cuticula artesanal ",
    "costo": 200,
    "margenBeneficio": 43,
    "stock": 20,
    "precio": 350,
    "ganancia": 150
  },
  {
    "imagen": "20230519_101401",
    "producto": "monomero tina ",
    "descripcion": "120 ml",
    "categoria": "manicura y pedicura",
    "nombreProducto": "monomero tina 120 ml",
    "costo": 980,
    "margenBeneficio": 30,
    "stock": 10,
    "precio": 1400,
    "ganancia": 420
  },
  {
    "imagen": "20230518_210003",
    "producto": "strass platedo x6 ",
    "descripcion": "1440 pc",
    "categoria": "manicura y pedicura",
    "nombreProducto": "strass platedo x6 1440 pc",
    "costo": 360,
    "margenBeneficio": 40,
    "stock": 8,
    "precio": 600,
    "ganancia": 240
  },
  {
    "imagen": "20230518_140108",
    "producto": "kapping navi",
    "descripcion": " 10 ml",
    "categoria": "manicura y pedicura",
    "nombreProducto": "kapping navi 10 ml",
    "costo": 900,
    "margenBeneficio": 40,
    "stock": 8,
    "precio": 1500,
    "ganancia": 600
  },
  {
    "imagen": "20230518_135836",
    "producto": "top navi ",
    "descripcion": "10 ml",
    "categoria": "manicura y pedicura",
    "nombreProducto": "top navi 10 ml",
    "costo": 900,
    "margenBeneficio": 40,
    "stock": 7,
    "precio": 1500,
    "ganancia": 600
  },
  {
    "imagen": "20230518_135836",
    "producto": "base  navi ",
    "descripcion": "10 ml ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "base  navi 10 ml ",
    "costo": 900,
    "margenBeneficio": 40,
    "stock": 7,
    "precio": 1500,
    "ganancia": 600
  },
  {
    "imagen": "IMG_20230527_151101_423",
    "producto": "lapiz para ceja con cepillo ",
    "descripcion": "negro o marron",
    "categoria": "maquillaje",
    "nombreProducto": "lapiz para ceja con cepillo negro o marron",
    "costo": 250,
    "margenBeneficio": 50,
    "stock": 4,
    "precio": 500,
    "ganancia": 250
  },
  {
    "imagen": "IMG_20230527_145953_528",
    "producto": "fibron para cejas ",
    "descripcion": "negro",
    "categoria": "maquillaje",
    "nombreProducto": "fibron para cejas negro",
    "costo": 350,
    "margenBeneficio": 45,
    "stock": 4,
    "precio": 640,
    "ganancia": 290
  },
  {
    "imagen": "IMG_20230523_134747_465",
    "producto": "lampara con porta foco",
    "descripcion": " color surtido",
    "categoria": "electronico",
    "nombreProducto": "lampara con porta foco color surtido",
    "costo": 3200,
    "margenBeneficio": 34,
    "stock": 4,
    "precio": 4850,
    "ganancia": 1650
  },
  {
    "imagen": "IMG_20230519_123500_763",
    "producto": " polvo aurora",
    "descripcion": " con pincel",
    "categoria": "manicura y pedicura",
    "nombreProducto": " polvo aurora con pincel",
    "costo": 280,
    "margenBeneficio": 40,
    "stock": 5,
    "precio": 470,
    "ganancia": 190
  },
  {
    "imagen": "IMG_20230519_114134_923",
    "producto": " capsula dual zeta ",
    "descripcion": "100 u",
    "categoria": "manicura y pedicura",
    "nombreProducto": " capsula dual zeta 100 u",
    "costo": 780,
    "margenBeneficio": 40,
    "stock": 10,
    "precio": 1300,
    "ganancia": 520
  },
  {
    "imagen": "IMG_20230519_103426_243",
    "producto": "tips city girls xxl",
    "descripcion": " 100 u",
    "categoria": "manicura y pedicura",
    "nombreProducto": "tips city girls xxl 100 u",
    "costo": 700,
    "margenBeneficio": 30,
    "stock": 10,
    "precio": 1000,
    "ganancia": 300
  },
  {
    "imagen": "IMG_20230519_103426_187",
    "producto": "tips global magic",
    "descripcion": " 100 u",
    "categoria": "manicura y pedicura",
    "nombreProducto": "tips global magic 100 u",
    "costo": 580,
    "margenBeneficio": 32,
    "stock": 8,
    "precio": 850,
    "ganancia": 270
  },
  {
    "imagen": "IMG_20230519_102421_590",
    "producto": "tips nails",
    "descripcion": " 100 u",
    "categoria": "manicura y pedicura",
    "nombreProducto": "tips nails 100 u",
    "costo": 450,
    "margenBeneficio": 44,
    "stock": 9,
    "precio": 800,
    "ganancia": 350
  },
  {
    "imagen": "20230403_180609",
    "producto": "estamlte para stamping las varanos ",
    "descripcion": " negro o blanco",
    "categoria": "manicura y pedicura",
    "nombreProducto": "estamlte para stamping las varanos  negro o blanco",
    "costo": 180,
    "margenBeneficio": 40,
    "stock": 4,
    "precio": 300,
    "ganancia": 120
  },
  {
    "imagen": "20230403_181035",
    "producto": "diamante para fotos ",
    "descripcion": "8 cm",
    "categoria": "manicura y pedicura",
    "nombreProducto": "diamante para fotos 8 cm",
    "costo": 900,
    "margenBeneficio": 30,
    "stock": 1,
    "precio": 1290,
    "ganancia": 390
  },
  {
    "imagen": "20230404_130904",
    "producto": "muestrario x 20",
    "descripcion": " rosa",
    "categoria": "manicura y pedicura",
    "nombreProducto": "muestrario x 20 rosa",
    "costo": 40,
    "margenBeneficio": 50,
    "stock": 10,
    "precio": 80,
    "ganancia": 40
  },
  {
    "imagen": "20230404_152658",
    "producto": "esmalte charm 15 ml",
    "descripcion": " consultar color ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "esmalte charm 15 ml consultar color ",
    "costo": 600,
    "margenBeneficio": 30,
    "stock": 20,
    "precio": 860,
    "ganancia": 260
  },
  {
    "imagen": "20230504_194159",
    "producto": "plancha adhesivo strass",
    "descripcion": " plateado",
    "categoria": "maquillaje",
    "nombreProducto": "plancha adhesivo strass plateado",
    "costo": 250,
    "margenBeneficio": 44,
    "stock": 4,
    "precio": 450,
    "ganancia": 200
  },
  {
    "imagen": "20230504_194254",
    "producto": "pigmento multiuso flour ",
    "descripcion": " x 6  ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "pigmento multiuso flour  x 6  ",
    "costo": 340,
    "margenBeneficio": 43,
    "stock": 10,
    "precio": 600,
    "ganancia": 260
  },
  {
    "imagen": "20230505_195711",
    "producto": "gel araña brilloso ",
    "descripcion": "consultar color",
    "categoria": "manicura y pedicura",
    "nombreProducto": "gel araña brilloso consultar color",
    "costo": 300,
    "margenBeneficio": 40,
    "stock": 6,
    "precio": 500,
    "ganancia": 200
  },
  {
    "imagen": "20230508_173855",
    "producto": "aplique conejo ",
    "descripcion": " x 2 u",
    "categoria": "manicura y pedicura",
    "nombreProducto": "aplique conejo  x 2 u",
    "costo": 180,
    "margenBeneficio": 35,
    "stock": 3,
    "precio": 280,
    "ganancia": 100
  },
  {
    "imagen": "20230508_174032",
    "producto": "aplique serpiente con strass/diamante ",
    "descripcion": " x 2 u",
    "categoria": "manicura y pedicura",
    "nombreProducto": "aplique serpiente con strass/diamante  x 2 u",
    "costo": 180,
    "margenBeneficio": 35,
    "stock": 10,
    "precio": 280,
    "ganancia": 100
  },
  {
    "imagen": "20230508_174132",
    "producto": "aplique lagarto ",
    "descripcion": " x 2 u",
    "categoria": "manicura y pedicura",
    "nombreProducto": "aplique lagarto  x 2 u",
    "costo": 180,
    "margenBeneficio": 35,
    "stock": 5,
    "precio": 280,
    "ganancia": 100
  },
  {
    "imagen": "20230508_174244",
    "producto": "aplique de pistola ",
    "descripcion": " x 2 u",
    "categoria": "manicura y pedicura",
    "nombreProducto": "aplique de pistola  x 2 u",
    "costo": 180,
    "margenBeneficio": 35,
    "stock": 5,
    "precio": 280,
    "ganancia": 100
  },
  {
    "imagen": "20230508_174309",
    "producto": "apliques moño ",
    "descripcion": " x 2 u",
    "categoria": "manicura y pedicura",
    "nombreProducto": "apliques moño  x 2 u",
    "costo": 180,
    "margenBeneficio": 35,
    "stock": 3,
    "precio": 280,
    "ganancia": 100
  },
  {
    "imagen": "20230511_183010",
    "producto": "fresa de carburo ",
    "descripcion": "para retirado",
    "categoria": "manicura y pedicura",
    "nombreProducto": "fresa de carburo para retirado",
    "costo": 1000,
    "margenBeneficio": 47,
    "stock": 6,
    "precio": 1890,
    "ganancia": 890
  },
  {
    "imagen": "20230511_183303",
    "producto": "molde azul",
    "descripcion": " x 30 u",
    "categoria": "manicura y pedicura",
    "nombreProducto": "molde azul x 30 u",
    "costo": 230,
    "margenBeneficio": 40,
    "stock": 20,
    "precio": 380,
    "ganancia": 150
  },
  {
    "imagen": "20230511_183510",
    "producto": "fresa de ceramica ",
    "descripcion": "consultar color",
    "categoria": "manicura y pedicura",
    "nombreProducto": "fresa de ceramica consultar color",
    "costo": 577,
    "margenBeneficio": 39,
    "stock": 10,
    "precio": 950,
    "ganancia": 373
  },
  {
    "imagen": "20230527_141345",
    "producto": "set de brillo ",
    "descripcion": " surtido x 12",
    "categoria": "manicura y pedicura",
    "nombreProducto": "set de brillo  surtido x 12",
    "costo": 400,
    "margenBeneficio": 58,
    "stock": 3,
    "precio": 950,
    "ganancia": 550
  },
  {
    "imagen": "20230527_141938",
    "producto": "apliques surtidos ",
    "descripcion": " consultar modelos ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "apliques surtidos  consultar modelos ",
    "costo": 300,
    "margenBeneficio": 45,
    "stock": 4,
    "precio": 550,
    "ganancia": 250
  },
  {
    "imagen": "20230530_105007",
    "producto": "set cola de sirena ",
    "descripcion": "  x 12 ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "set cola de sirena   x 12 ",
    "costo": 300,
    "margenBeneficio": 50,
    "stock": 1,
    "precio": 600,
    "ganancia": 300
  },
  {
    "imagen": "20230601_194059",
    "producto": "brillo labial pink 21",
    "descripcion": "consultar color",
    "categoria": "maquillaje",
    "nombreProducto": "brillo labial pink 21consultar color",
    "costo": 260,
    "margenBeneficio": 46,
    "stock": 5,
    "precio": 480,
    "ganancia": 220
  },
  {
    "imagen": "20230601_203454",
    "producto": "esmalte top coat comun ",
    "descripcion": "cherimoya ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "esmalte top coat comun cherimoya ",
    "costo": 300,
    "margenBeneficio": 40,
    "stock": 4,
    "precio": 500,
    "ganancia": 200
  },
  {
    "imagen": "20230601_203510",
    "producto": "tratamiento fortalecedor ",
    "descripcion": " cherimoya",
    "categoria": "manicura y pedicura",
    "nombreProducto": "tratamiento fortalecedor  cherimoya",
    "costo": 330,
    "margenBeneficio": 40,
    "stock": 3,
    "precio": 550,
    "ganancia": 220
  },
  {
    "imagen": "20230601_204006",
    "producto": "torno profesional ",
    "descripcion": "2000 w",
    "categoria": "electronico",
    "nombreProducto": "torno profesional 2000 w",
    "costo": 8000,
    "margenBeneficio": 30,
    "stock": 1,
    "precio": 11430,
    "ganancia": 3430
  },
  {
    "imagen": "20230313_115001",
    "producto": "perfec liner ",
    "descripcion": "cherimoya ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "perfec liner cherimoya ",
    "costo": 350,
    "margenBeneficio": 50,
    "stock": 4,
    "precio": 700,
    "ganancia": 350
  },
  {
    "imagen": "20230601_204043",
    "producto": "polimero acrifine",
    "descripcion": "consultar tono",
    "categoria": "manicura y pedicura",
    "nombreProducto": "polimero acrifineconsultar tono",
    "costo": 2560,
    "margenBeneficio": 30,
    "stock": 6,
    "precio": 3660,
    "ganancia": 1100
  },
  {
    "imagen": "20230601_205240",
    "producto": "kit permanente pestañas ",
    "descripcion": "original lash ",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "kit permanente pestañas original lash ",
    "costo": 1320,
    "margenBeneficio": 40,
    "stock": 1,
    "precio": 2200
  },
  {
    "imagen": "20230601_205424",
    "producto": "kit lifting ",
    "descripcion": " original lash",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "kit lifting  original lash",
    "costo": 2000,
    "margenBeneficio": 35,
    "stock": 1,
    "precio": 3080
  },
  {
    "imagen": "20220904_201849",
    "producto": "guantes de nitrilo ",
    "descripcion": " x 2 u",
    "categoria": "manicura y pedicura",
    "nombreProducto": "guantes de nitrilo  x 2 u",
    "costo": 20,
    "margenBeneficio": 70,
    "stock": 20,
    "precio": 70
  },
  {
    "imagen": "20220930_102501",
    "producto": "stiker surtidos ",
    "descripcion": " consultar diseño",
    "categoria": "manicura y pedicura",
    "nombreProducto": "stiker surtidos  consultar diseño",
    "costo": 140,
    "margenBeneficio": 38,
    "stock": 20,
    "precio": 230
  },
  {
    "imagen": "20221124_195135",
    "producto": "cepillo para uñas",
    "descripcion": " x 1 ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "cepillo para uñas x 1 ",
    "costo": 110,
    "margenBeneficio": 40,
    "stock": 10,
    "precio": 180
  },
  {
    "imagen": "20220904_205104",
    "producto": "primer acryfine ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "primer acryfine ",
    "costo": 1000,
    "margenBeneficio": 30,
    "stock": 2,
    "precio": 1430
  },
  {
    "imagen": "20221124_195229",
    "producto": "limas para tornos ",
    "descripcion": " x 50 u cuadrado",
    "categoria": "manicura y pedicura",
    "nombreProducto": "limas para tornos  x 50 u cuadrado",
    "costo": 405,
    "margenBeneficio": 40,
    "stock": 9,
    "precio": 680
  },
  {
    "imagen": "20221124_195249",
    "producto": "gel dual qbd ",
    "descripcion": " consultar tono",
    "categoria": "manicura y pedicura",
    "nombreProducto": "gel dual qbd  consultar tono",
    "costo": 690,
    "margenBeneficio": 35,
    "stock": 8,
    "precio": 1060
  },
  {
    "imagen": "20221124_195631",
    "producto": "capuchones para pies ",
    "descripcion": " color surtido",
    "categoria": "manicura y pedicura",
    "nombreProducto": "capuchones para pies  color surtido",
    "costo": 480,
    "margenBeneficio": 30,
    "stock": 5,
    "precio": 690
  },
  {
    "imagen": "20221124_201842",
    "producto": "dotting",
    "descripcion": " x 5 u",
    "categoria": "manicura y pedicura",
    "nombreProducto": "dotting x 5 u",
    "costo": 350,
    "margenBeneficio": 40,
    "stock": 8,
    "precio": 580
  },
  {
    "imagen": "20221124_201842",
    "producto": "dotting",
    "descripcion": " x 1 u surtido",
    "categoria": "manicura y pedicura",
    "nombreProducto": "dotting x 1 u surtido",
    "costo": 70,
    "margenBeneficio": 48,
    "stock": 10,
    "precio": 130
  },
  {
    "imagen": "20221124_202516",
    "producto": "tips eloise sonrisa cuadrados ",
    "descripcion": " x 100 u",
    "categoria": "manicura y pedicura",
    "nombreProducto": "tips eloise sonrisa cuadrados  x 100 u",
    "costo": 580,
    "margenBeneficio": 35,
    "stock": 5,
    "precio": 890
  },
  {
    "imagen": "20221124_202604",
    "producto": "tip sonrisa eloise estiletto",
    "descripcion": " x 100 u",
    "categoria": "manicura y pedicura",
    "nombreProducto": "tip sonrisa eloise estiletto x 100 u",
    "costo": 580,
    "margenBeneficio": 35,
    "stock": 3,
    "precio": 890
  },
  {
    "imagen": "20230105_192039",
    "producto": "decoracion confetti paris night",
    "descripcion": " consultar color ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "decoracion confetti paris night consultar color ",
    "costo": 580,
    "margenBeneficio": 35,
    "stock": 3,
    "precio": 890
  },
  {
    "imagen": "20230206_234637",
    "producto": "polvo aurora s/ paris nigth ",
    "descripcion": " blanco perlado",
    "categoria": "manicura y pedicura",
    "nombreProducto": "polvo aurora s/ paris nigth  blanco perlado",
    "costo": 400,
    "margenBeneficio": 40,
    "stock": 3,
    "precio": 670
  },
  {
    "imagen": "20230207_000717",
    "producto": "capsulas koper mandorla rusa",
    "descripcion": " x 120 u",
    "categoria": "manicura y pedicura",
    "nombreProducto": "capsulas koper mandorla rusa x 120 u",
    "costo": 1000,
    "margenBeneficio": 3,
    "stock": 5,
    "precio": 1030
  },
  {
    "imagen": "20230225_213637",
    "producto": "tips eloise para soft gel ",
    "descripcion": "estiletto x 100u",
    "categoria": "manicura y pedicura",
    "nombreProducto": "tips eloise para soft gel estiletto x 100u",
    "costo": 500,
    "margenBeneficio": 49,
    "stock": 5,
    "precio": 980
  },
  {
    "imagen": "20230225_214216",
    "producto": "carrusel deco metal",
    "descripcion": "flour ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "carrusel deco metalflour ",
    "costo": 180,
    "margenBeneficio": 40,
    "stock": 3,
    "precio": 300
  },
  {
    "imagen": "20230227_120305",
    "producto": "set de apliques cyg  animales kawaii",
    "descripcion": " surtido",
    "categoria": "manicura y pedicura",
    "nombreProducto": "set de apliques cyg  animales kawaii surtido",
    "costo": 480,
    "margenBeneficio": 40,
    "stock": 3,
    "precio": 800
  },
  {
    "imagen": "20230227_140911",
    "producto": "set de apliques cyg osito kawaii",
    "descripcion": " surtido",
    "categoria": "manicura y pedicura",
    "nombreProducto": "set de apliques cyg osito kawaii surtido",
    "costo": 480,
    "margenBeneficio": 40,
    "stock": 2,
    "precio": 800
  },
  {
    "imagen": "20230227_143107",
    "producto": "set de confetti p/ encapsular ",
    "descripcion": " flour ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "set de confetti p/ encapsular  flour ",
    "costo": 350,
    "margenBeneficio": 40,
    "stock": 4,
    "precio": 580
  },
  {
    "imagen": "20230227_144414",
    "producto": "pegamento pestaña navina ",
    "descripcion": " azul",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "pegamento pestaña navina  azul",
    "costo": 1880,
    "margenBeneficio": 35,
    "stock": 3,
    "precio": 2890
  },
  {
    "imagen": "20230303_202943",
    "producto": "pincel liner",
    "descripcion": " x 1 surtido",
    "categoria": "manicura y pedicura",
    "nombreProducto": "pincel liner x 1 surtido",
    "costo": 70,
    "margenBeneficio": 45,
    "stock": 7,
    "precio": 130
  },
  {
    "imagen": "20230306_175356",
    "producto": "prep nails show ",
    "descripcion": " 8 ml",
    "categoria": "manicura y pedicura",
    "nombreProducto": "prep nails show  8 ml",
    "costo": 800,
    "margenBeneficio": 40,
    "stock": 3,
    "precio": 1330
  },
  {
    "imagen": "20230308_105122",
    "producto": "semi cherimoya ",
    "descripcion": "8 ml",
    "categoria": "manicura y pedicura",
    "nombreProducto": "semi cherimoya 8 ml",
    "costo": 770,
    "margenBeneficio": 30,
    "stock": 5,
    "precio": 1100
  },
  {
    "imagen": "20230309_102616",
    "producto": "apliques p/ uñas ",
    "descripcion": " x 2 u consultar",
    "categoria": "manicura y pedicura",
    "nombreProducto": "apliques p/ uñas  x 2 u consultar",
    "costo": 60,
    "margenBeneficio": 67,
    "stock": 16,
    "precio": 180
  },
  {
    "imagen": "20230317_192612",
    "producto": "tips francesitas ",
    "descripcion": " 50 u",
    "categoria": "manicura y pedicura",
    "nombreProducto": "tips francesitas  50 u",
    "costo": 20,
    "margenBeneficio": 50,
    "stock": 30,
    "precio": 40
  },
  {
    "imagen": "20230403_113108",
    "producto": "tips eloise en caja  coffin",
    "descripcion": " x 500 u",
    "categoria": "manicura y pedicura",
    "nombreProducto": "tips eloise en caja  coffin x 500 u",
    "costo": 1980,
    "margenBeneficio": 33,
    "stock": 3,
    "precio": 2960
  },
  {
    "imagen": "20230403_113336",
    "producto": "tips eloise coffin",
    "descripcion": "color natural x 100 u",
    "categoria": "manicura y pedicura",
    "nombreProducto": "tips eloise coffincolor natural x 100 u",
    "costo": 500,
    "margenBeneficio": 40,
    "stock": 5,
    "precio": 830
  },
  {
    "imagen": "20230403_180524",
    "producto": "polimero qbd envase transpa",
    "descripcion": " 26 gr consultar color",
    "categoria": "manicura y pedicura",
    "nombreProducto": "polimero qbd envase transpa 26 gr consultar color",
    "costo": 480,
    "margenBeneficio": 50,
    "stock": 3,
    "precio": 960
  },
  {
    "imagen": "IMG_20230527_153522_562",
    "producto": "corector  de ojera liquido matte",
    "descripcion": " consultar tonos",
    "categoria": "manicura y pedicura",
    "nombreProducto": "corector  de ojera liquido matte consultar tonos",
    "costo": 300,
    "margenBeneficio": 45,
    "stock": 3,
    "precio": 550
  },
  {
    "imagen": "20230605_100411",
    "producto": "solucion poligel lfme",
    "descripcion": "100 ml ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "solucion poligel lfme100 ml ",
    "costo": 290,
    "margenBeneficio": 40,
    "stock": 10,
    "precio": 480
  },
  {
    "imagen": "20230608_125706",
    "producto": "papel aluminio",
    "descripcion": " 50 m",
    "categoria": "manicura y pedicura",
    "nombreProducto": "papel aluminio 50 m",
    "costo": 540,
    "margenBeneficio": 45,
    "stock": 4,
    "precio": 980
  },
  {
    "imagen": "20230605_113923",
    "producto": "polvo espejo ",
    "descripcion": "plateado",
    "categoria": "manicura y pedicura",
    "nombreProducto": "polvo espejo plateado",
    "costo": 280,
    "margenBeneficio": 38,
    "stock": 4,
    "oferta": 1,
    "precio": 450
  },
  {
    "imagen": "20230605_113722",
    "producto": "polvo powerd holografico",
    "descripcion": "unico color ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "polvo powerd holograficounico color ",
    "costo": 280,
    "margenBeneficio": 38,
    "stock": 10,
    "oferta": 1,
    "precio": 450
  },
  {
    "imagen": "20230602_140844",
    "producto": "polvo aurora colores  paris ",
    "descripcion": " x 1 u",
    "categoria": "manicura y pedicura",
    "nombreProducto": "polvo aurora colores  paris  x 1 u",
    "costo": 250,
    "margenBeneficio": 50,
    "stock": 24,
    "precio": 500
  },
  {
    "imagen": "20230608_173843",
    "producto": "fimos deco ",
    "descripcion": " x 12 u",
    "categoria": "manicura y pedicura",
    "nombreProducto": "fimos deco  x 12 u",
    "costo": 280,
    "margenBeneficio": 45,
    "stock": 4,
    "precio": 510
  },
  {
    "imagen": "20230609_104225",
    "producto": "limas espoge ",
    "descripcion": "100/180",
    "categoria": "manicura y pedicura",
    "nombreProducto": "limas espoge 100/180",
    "costo": 137,
    "margenBeneficio": 50,
    "stock": 10,
    "precio": 270
  },
  {
    "imagen": "20230609_133338",
    "producto": "torno con usb ",
    "descripcion": "rosa ",
    "categoria": "electronico",
    "nombreProducto": "torno con usb rosa ",
    "costo": 2700,
    "margenBeneficio": 30,
    "stock": 3,
    "precio": 3860
  },
  {
    "imagen": "20230609_185117",
    "producto": "semipermanente navi",
    "descripcion": "consultar colores",
    "categoria": "manicura y pedicura",
    "nombreProducto": "semipermanente naviconsultar colores",
    "costo": 900,
    "margenBeneficio": 40,
    "stock": 5,
    "precio": 1500
  },
  {
    "imagen": "20230609_193004",
    "producto": "porta straas acrilico ",
    "descripcion": " x 24 ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "porta straas acrilico  x 24 ",
    "costo": 850,
    "margenBeneficio": 40,
    "stock": 2,
    "precio": 1420
  },
  {
    "imagen": "20230610_112602",
    "producto": "medias perlas paris ",
    "descripcion": "blancas ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "medias perlas paris blancas ",
    "costo": 550,
    "margenBeneficio": 35,
    "stock": 2,
    "precio": 850
  },
  {
    "imagen": "20230602_174614",
    "producto": "pinzas navina volumen ruso",
    "descripcion": " x 1 ",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "pinzas navina volumen ruso x 1 ",
    "costo": 1980,
    "margenBeneficio": 30,
    "stock": 2,
    "precio": 2830
  },
  {
    "imagen": "20230608_125948",
    "producto": "capsulas stiletto ",
    "descripcion": " 120 u ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "capsulas stiletto  120 u ",
    "costo": 680,
    "margenBeneficio": 40,
    "stock": 2,
    "precio": 1130
  },
  {
    "imagen": "20230608_130153",
    "producto": "strass mariposa",
    "descripcion": " x 1 u",
    "categoria": "manicura y pedicura",
    "nombreProducto": "strass mariposa x 1 u",
    "costo": 84,
    "margenBeneficio": 45,
    "stock": 8,
    "precio": 150
  },
  {
    "imagen": "20230610_155554",
    "producto": "top premiun cherimoya matte ",
    "descripcion": "tapa negra ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "top premiun cherimoya matte tapa negra ",
    "costo": 1500,
    "margenBeneficio": 30,
    "stock": 2,
    "oferta": 1,
    "precio": 2140
  },
  {
    "imagen": "20230613_100933",
    "producto": "removedor las varanos ",
    "descripcion": " 120 ml",
    "categoria": "manicura y pedicura",
    "nombreProducto": "removedor las varanos  120 ml",
    "costo": 560,
    "margenBeneficio": 30,
    "stock": 10,
    "precio": 800
  },
  {
    "imagen": "20230613_100951",
    "producto": "removedor las varanos ",
    "descripcion": " 250 ml",
    "categoria": "manicura y pedicura",
    "nombreProducto": "removedor las varanos  250 ml",
    "costo": 1000,
    "margenBeneficio": 30,
    "stock": 8,
    "precio": 1430
  },
  {
    "imagen": "20230613_101026",
    "producto": "lapiz dermo ",
    "descripcion": " marron  o negro",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "lapiz dermo  marron  o negro",
    "costo": 190,
    "margenBeneficio": 45,
    "stock": 10,
    "precio": 350
  },
  {
    "imagen": "20230613_101056",
    "producto": "removedor magico cherimoya",
    "descripcion": "frasco vidrio",
    "categoria": "manicura y pedicura",
    "nombreProducto": "removedor magico cherimoyafrasco vidrio",
    "costo": 1000,
    "margenBeneficio": 35,
    "stock": 3,
    "precio": 1540
  },
  {
    "imagen": "20230613_101109",
    "producto": "porta pincel corona ",
    "descripcion": "  dorado",
    "categoria": "manicura y pedicura",
    "nombreProducto": "porta pincel corona   dorado",
    "costo": 500,
    "margenBeneficio": 50,
    "stock": 2,
    "precio": 1000
  },
  {
    "imagen": "20230613_101156",
    "producto": "gel solido navi",
    "descripcion": "20 ml",
    "categoria": "manicura y pedicura",
    "nombreProducto": "gel solido navi20 ml",
    "costo": 1900,
    "margenBeneficio": 30,
    "stock": 4,
    "oferta": 1,
    "precio": 2710
  },
  {
    "imagen": "20230613_101207",
    "producto": "pegamento de strass ",
    "descripcion": " charm ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "pegamento de strass  charm ",
    "costo": 480,
    "margenBeneficio": 30,
    "stock": 5,
    "precio": 690
  },
  {
    "imagen": "20230613_101232",
    "producto": "cabina manual paris night",
    "descripcion": "36 w ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "cabina manual paris night36 w ",
    "costo": 2300,
    "margenBeneficio": 35,
    "stock": 2,
    "precio": 3540
  },
  {
    "imagen": "20230613_101331",
    "producto": "corta uñas flor ",
    "descripcion": "metal",
    "categoria": "manicura y pedicura",
    "nombreProducto": "corta uñas flor metal",
    "costo": 150,
    "margenBeneficio": 40,
    "stock": 3,
    "precio": 250
  },
  {
    "imagen": "20230613_101353",
    "producto": "biguidies x 5 u",
    "descripcion": " surtido",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "biguidies x 5 u surtido",
    "costo": 380,
    "margenBeneficio": 40,
    "stock": 2,
    "precio": 630
  },
  {
    "imagen": "20230325_150310",
    "producto": "pincel almendra paris night",
    "descripcion": "consultar tono",
    "categoria": "manicura y pedicura",
    "nombreProducto": "pincel almendra paris nightconsultar tono",
    "costo": 500,
    "margenBeneficio": 40,
    "stock": 2,
    "precio": 830
  },
  {
    "imagen": "20230413_182525",
    "producto": "kit lifting ",
    "descripcion": " iconsing ",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "kit lifting  iconsing ",
    "costo": 3780,
    "margenBeneficio": 30,
    "stock": 2,
    "precio": 5400
  },
  {
    "imagen": "20230406_095951",
    "producto": "cepillo de  pestañas ",
    "descripcion": " color surtido",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "cepillo de  pestañas  color surtido",
    "costo": 260,
    "margenBeneficio": 40,
    "stock": 2,
    "precio": 430
  },
  {
    "imagen": "IMG_20230614_134051_461",
    "producto": "pinzas  pestañas ",
    "descripcion": "consultar ",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "pinzas  pestañas consultar ",
    "costo": 400,
    "margenBeneficio": 49,
    "stock": 6,
    "precio": 780
  },
  {
    "imagen": "20230614_120157",
    "producto": "pegamento neicha",
    "descripcion": " 2 gr",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "pegamento neicha 2 gr",
    "costo": 5000,
    "margenBeneficio": 30,
    "stock": 2,
    "oferta": 1,
    "precio": 7140
  },
  {
    "imagen": "20230614_115856",
    "producto": "moldes rosa ",
    "descripcion": " x 50 u ",
    "categoria": "manicura y pedicura",
    "nombreProducto": "moldes rosa  x 50 u ",
    "costo": 180,
    "margenBeneficio": 55,
    "stock": 25,
    "precio": 400
  },
  {
    "imagen": "20230614_114736",
    "producto": "guantes de nitrilo ",
    "descripcion": "rosa",
    "categoria": "manicura y pedicura",
    "nombreProducto": "guantes de nitrilo rosa",
    "costo": 990,
    "margenBeneficio": 42,
    "stock": 4,
    "precio": 1710
  },
  {
    "imagen": "20230613_140825",
    "producto": "botella curva para pestañas",
    "descripcion": "consultar tonos",
    "categoria": "pestañas y cejas ",
    "nombreProducto": "botella curva para pestañasconsultar tonos",
    "costo": 490,
    "margenBeneficio": 37,
    "stock": 3,
    "precio": 780
  }
]